---
- hosts: www
  sudo: True
  tasks:
    - name: install $item
      action: yum pkg=$item state=latest
      with_items:
        - MySQL-python
        - mod_wsgi
        - httpd
        - mod_ssl
        - awstats
    - name: Configure selinux
      action: seboolean persistent=yes name=httpd_can_network_connect state=true
      ignore_errors: True
    - name: Create apache directory
      action: file state=directory path=/srv/web
    - name: Ensure apache is enabled
      action: service name=httpd state=started
    - name: Install SSL certificate
      action: copy src=../private/synhak.org.crt dest=/etc/pki/tls/certs/synhak.org.crt
      notify:
        - reload apache
    - name: Install SSL key
      action: copy src=../private/synhak.org.key dest=/etc/pki/tls/private/synhak.org.key
      notify:
        - reload apache
    - name: Update general apache configuration
      action: template src=../config/apache.conf dest=/etc/httpd/conf/httpd.conf
      notify:
        - reload apache
    - name: Update synhak.org apache configuration
      action: copy src=../config/synhak.org.conf dest=/etc/httpd/conf.d/synhak.org.conf
      notify:
        - reload apache
    - name: Un-disable UserDir
      action: lineinfile dest=/etc/httpd/conf/httpd.conf regexp="UserDir disabled" state=absent
      notify:
        - reload apache
    - name: Configure SSL certificate
      action: lineinfile dest=/etc/httpd/conf.d/ssl.conf regexp="^SSLCertificateFile" line="SSLCertificateFile /etc/pki/tls/certs/synhak.org.crt"
      notify:
        - reload apache
    - name: Configure SSL key
      action: lineinfile dest=/etc/httpd/conf.d/ssl.conf regexp="^SSLCertificateKeyFile" line="SSLCertificateKeyFile /etc/pki/tls/private/synhak.org.key"
      notify:
        - reload apache
    - name: configure awstats
      action: template src=../config/awstats.conf dest=/etc/awstats/awstats.${inventory_hostname}.conf
    - name: install google analytics token
      action: copy src=../config/google274c79f3d27b61a5.html dest=/var/www/html/google274c79f3d27b61a5.html
  handlers:
    - name: reload apache
      action: service name=httpd state=reloaded
