---
- hosts: all
  sudo: True
  vars_files:
    - ../config/sysadmins.yml
  tasks:
    - name: Install packages
      action: yum pkg=$item state=latest
      with_items:
        - libselinux-python
      tags:
        - packages
    - name: Create sysadmin users
      action: user name=${item.name} state=present groups="wheel" append=true
      with_items: $sysadmins
    - name: install sysadmin keys
      action: authorized_key user=${item.name} key="${item.key}"
      with_items: $sysadmins
    - name: configure sudo
#This is how you escape colons in ansible yaml. Yeah.
      action: 'lineinfile dest=/etc/sudoers regexp="^%wheel" line="%wheel ALL=(ALL) NOPASSWD: ALL"'
    - name: enable EPEL
      action: copy src=../config/epel.repo dest=/etc/yum.repos.d/epel.repo
    - name: configure hostname
      action: lineinfile name=/etc/sysconfig/network regexp=^HOSTNAME= line=HOSTNAME=$inventory_hostname insertafter=EOF state=present
      notify:
      - set hostname
    - name: Import RPM keys
      action: rpm_key state=present key=$item
      with_items:
        - /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
        - https://fedoraproject.org/static/0608B895.txt
    - name: install $item
      action: yum pkg=$item state=latest
      with_items:
        - git
        - epel-release
    - name: update motd
      action: template src=../config/motd dest=/etc/motd
  handlers:
    - name: set hostname
      action: command hostname $inventory_hostname
