---
- hosts: www
  sudo: True
  vars_files:
    - '../private/mailman.yml'
  vars:
    - lists:
      - announce
      - discuss
      - board
      - members
      - sysadmin
      - mailman
  tasks:
    - name: update $item
      action: yum pkg=$item state=latest
      with_items:
        - mailman
        - postfix
    - name: install basic aliases
      action: copy src=../config/aliases dest=/etc/synhak-aliases
      notify:
        - run newaliases
    - name: Configure postfix
      action: copy src=../config/main.cf dest=/etc/postfix/main.cf
      notify:
        - restart postfix
    - name: Configure mailman
      action: copy src=../config/mm_cfg.py dest=/usr/lib/mailman/Mailman/mm_cfg.py
    - name: create lists
      action: command creates=/var/lib/mailman/lists/${item}/config.pck /usr/lib/mailman/bin/newlist -q ${item} sysadmin@synhak.org ${admin_pw}
      register: mm_output
      with_items: $lists
    - name: store list configuration for $item
      action: copy src=../config/mailman/${item.item}.cfg dest=/etc/mailman/${item.item}.cfg
      with_items: $nm_output
      notify:
        - configure lists
    - name: Ensure service $item is enabled and running
      action: service name=$item state=started
      with_items:
        - mailman
        - postfix
    - name: update local list configuration
      action: fetch src=/etc/mailman/${item}.cfg dest=../config/mailman/${item}.cfg.d
      with_items: $lists
  handlers:
    - name: configure lists
      action: command echo /usr/lib/mailman/bin/config_list -i /etc/mailman/${item.item}.cfg ${item.item}
      with_items: $nm_output
    - name: restart postfix
      action: service name=postfix state=reloaded
    - name: run newaliases
      action: command newaliases
