---
- hosts: mail
  sudo: True
  vars_files:
    - '../private/mailman.yml'
  vars:
    - lists:
      - announce
      - discuss
      - board
      - members
      - sysadmin
      - mailman
  tasks:
    - name: update $item
      action: yum pkg=$item state=latest
      with_items:
        - mailman
        - postfix
        - nginx
    - name: configure nginx
      action: copy src=../config/lists.synhak.org.conf dest=/etc/nginx/conf.d/lists.synhak.org.conf
      notify:
        - restart nginx
    - name: install basic aliases
      action: copy src=../config/aliases dest=/etc/synhak-aliases
      notify:
        - run newaliases
    - name: Configure postfix
      action: copy src=../config/main.cf dest=/etc/postfix/main.cf
      notify:
        - restart postfix
    - name: Configure mailman
      action: copy src=../config/mm_cfg.py dest=/usr/lib/mailman/Mailman/mm_cfg.py
    - name: configure thttpd
      action: copy src=../config/mailman-thttpd.conf dest=/etc/thttpd.conf
      notify:
        - restart thttpd
    - name: Ensure service $item is enabled and running
      action: service name=$item state=started
      with_items:
        - mailman
        - postfix
        - nginx
        - thttpd
  handlers:
    - name: restart postfix
      action: service name=postfix state=reloaded
    - name: run newaliases
      action: command newaliases
    - name: restart nginx
      action: service name=nginx state=reloaded
    - name: restart thttpd
      action: service name=thttpd state=reloaded
