---
- hosts: www
  sudo: True
  vars_files:
   - ../private/spiff-settings.yml
  tasks:
    - name: install packages
      action: yum pkg=$item state=latest
      with_items:
        - python-pip
        - python-virtualenv
        - mysql-devel
        - python-devel
        - gcc
    - name: deploy spiff
      action: git repo=git://github.com/SYNHAK/spiff.git dest=/srv/spiff/ version=HEAD
      notify:
      - reload wsgi
      - spiff syncdb
      - spiff migrate
      tags:
        - quick
    - name: create spiff virtualenv
      action: command creates=/srv/virtualenv/bin/activate virtualenv /srv/virtualenv/
    - name: build spiff virtualenv
      action: shell source /srv/virtualenv/bin/activate; pip install -r /srv/spiff/pip-requirements
    - name: install python-mysql to spiff virtualenv
      action: shell source /srv/virtualenv/bin/activate; pip install MySQL-python
    - name: configure spiff
      action: template src=../config/local_settings.py dest=/srv/spiff/spiff/local_settings.py
      notify:
      - reload wsgi
      - spiff syncdb
      - spiff migrate
  handlers:
    - name: reload wsgi
      action: command touch /srv/spiff/spiff/wsgi.py
    - name: spiff migrate
      action: shell source /srv/virtualenv/bin/activate; /srv/spiff/manage.py migrate --merge
      delegate_to: www-0
    - name: spiff syncdb
      action: shell source /srv/virtualenv/bin/activate; /srv/spiff/manage.py syncdb --all --noinput
      delegate_to: www-0
