---
- hosts: kiosk
  sudo: False
  user: root
  tasks:
    - name: install packages
      action: yum pkg=$item state=latest
      with_items:
        - spacekit-kiosk
        - bonehead
    - name: configure bonehead
      action: copy src=../config/bonehead.cfg dest=/etc/bonehead.cfg
