---
- hosts: www
  sudo: True
  vars:
    mediawiki_branch: "synhak-1.21.0"
    mw_git: "https://gerrit.wikimedia.org/r/p/mediawiki/extensions"
    mw_prefix: "/srv/web/w"
  vars_files:
    - ../private/mediawiki-settings.yml
  tasks:
    - name: Install PHP packages
      action: yum pkg=$item state=latest
      with_items:
        - php
        - php-pecl-apc
        - php-mysql
        - php-xml
        - librsvg2
        - ImageMagick
    - name: Update mediawiki
      action: git repo=https://github.com/SYNHAK/mediawiki.git dest=${mw_prefix} version=${mediawiki_branch}
      notify: 
        - Run update.php
    - name: Update ConfirmEdit extension
      action: git repo=${mw_git}/ConfirmEdit.git dest=${mw_prefix}/extensions/ConfirmEdit
    - name: Update ParserFunctions extension
      action: git repo=${mw_git}/ParserFunctions.git dest=${mw_prefix}/extensions/ParserFunctions
    - name: Update Nuke extension
      action: git repo=${mw_git}/Nuke.git dest=${mw_prefix}/extensions/Nuke
    - name: Update Gadgets extension
      action: git repo=${mw_git}/Gadgets.git dest=${mw_prefix}/extensions/Gadgets
    - name: Update googleAnalytics extension
      action: git repo=${mw_git}/googleAnalytics.git dest=${mw_prefix}/extensions/googleAnalytics
    - name: Update secured_html extension
      action: copy src=../config/Secured_HTML.php dest=${mw_prefix}/extensions/Secured_HTML.php
    - name: Update googleagenda extension
      action: copy src=../config/googleAgenda.php dest=${mw_prefix}/extensions/googleAgenda.php
    - name: Update RSS extension
      action: git repo=${mw_git}/RSS.git dest=${mw_prefix}/extensions/RSS
    - name: Update External Data extension
      action: git repo=${mw_git}/ExternalData.git dest=${mw_prefix}/extensions/ExternalData
    - name: Update AWS extension
      action: git repo=${mw_git}/AWS.git  dest=${mw_prefix}/extensions/AWS
    - name: Install composer crap
      action: shell chdir=${mw_prefix}/extensions/AWS creates=${mw_prefix}/composer.phar curl -sS https://getcomposer.org/installer | php
    - name: Install composer crap crap
      action: command chdir=${mw_prefix}/extensions/AWS php composer.phar install
    - name: Update mediawiki configuration
      action: template src=../config/LocalSettings.php dest=${mw_prefix}/LocalSettings.php
  handlers:
    - name: Run update.php
      action: command chdir=${mw_prefix}/maintenance/ php update.php
