---
- hosts: www
  sudo: True
  tasks:
    - name: install $item
      action: yum pkg=$item state=latest
      with_items:
        - MySQL-python
        - mod_wsgi
        - nginx
        - php-fpm
    - name: Configure selinux
      action: seboolean persistent=yes name=httpd_can_network_connect state=true
      ignore_errors: True
    - name: Create nginx directory
      action: file state=directory path=/srv/web
    - name: Ensure nginx is enabled
      action: service name=nginx state=started
    - name: Ensure php-fpm is enabled
      action: service name=php-fpm state=started
    - name: Install SSL certificate
      action: copy src=../private/synhak.org.crt dest=/etc/pki/tls/certs/synhak.org.crt
      notify:
        - reload nginx
    - name: Install SSL key
      action: copy src=../private/synhak.org.key dest=/etc/pki/tls/private/synhak.org.key
      notify:
        - reload nginx
    - name: Update general nginx configuration
      action: template src=../config/nginx.conf dest=/etc/nginx/nginx.conf
      notify:
        - reload nginx
    - name: Update synhak.org nginx configuration
      action: template src=../config/synhak.org.conf dest=/etc/nginx/conf.d/default.conf
      notify:
        - reload nginx
  handlers:
    - name: reload nginx
      action: service name=nginx state=reloaded
