---
- hosts: admin
  sudo: true
  vars_files:
    - ../private/phong-config.yml
  tasks:
    - name: install packages
      action: yum pkg=$item state=latest
      with_items:
        - python-virtualenv
        - python-pip
    - name: create phong user
      action: user name=phong comment="Phong!" state=present home=/srv/phong
    - name: Install phong helper script
      action: copy src=../scripts/run-phong.sh dest=/srv/phong/run-phong.sh
    - name: update phong
      action: git repo=https://github.com/SYNHAK/synhak-documents.git dest=/srv/phong/synhak-documents/
      tags:
        - quick
    - name: configure phong
      action: template src=../config/phong-settings.py dest=/srv/phong/synhak-documents/tools/settings.py
    - name: setup phong virtualenv
      action: command virtualenv /srv/phong-virtualenv/
    - name: install phong virtualenv
      action: command /srv/phong/run-phong.sh pip install -r /srv/phong/phong/pip-requirements
    - name: meetbot crontab
      action: cron name="Meetbot" user=phong minute=26 hour=8 job="/srv/phong/run-phong.sh /srv/phong/phong/phong.py meetings -w -r -m >/dev/null"
    - name: event administrivia
      action: cron name="Events" user=phong minute=12 hour=3 job="/srv/phong/run-phong.sh  /srv/phong/phong/phong.py new-event-mails >/dev/null"
#    - name: financial report wiki cron
#      action: cron name="Daily fiscal wiki page" user=phong minute=0 hour=2 job="/srv/phong/synhak-documents/tools/fiscal-summary.py -w /home/treasurer/public_html/synhak.xml.gnucash >/dev/null"
#    - name: discuss monthly fiscal report
#      action: cron name="monthly fiscal report" user=phong day=1 minute=30 hour=2 job="/srv/phong/synhak-documents/tools/fiscal-summary.py -e discuss@synhak.org /home/treasurer/public_html/synhak.xml.gnucash >/dev/null"
#    - name: treasurer tuesday fiscal report
#      action: cron name="tuesday fiscal report" user=phong minute=0 hour=12 weekday=2 job="/srv/phong/synhak-documents/tools/fiscal-summary.py -e treasurer@synhak.org /home/treasurer/public_html/synhak.xml.gnucash >/dev/null"
