---
- hosts: www
  sudo: True
  tasks:
    - name: deploy spiff
      action: git repo=git://github.com/synhak/spiff.git dest=/srv/spiff/ version=HEAD
      notify:
      - reload wsgi
      - spiff syncdb
  handlers:
    - name: reload wsgi
      action: command touch /srv/spiff/spiff/wsgi.py
    - name: spiff syncdb
      action: command /srv/spiff/manage.py syncdb --migrate --noinput
