---
- hosts: www
  sudo: True
  tasks:
    - name: install $item
      action: yum pkg=$item state=latest
      with_items:
        - MySQL-python
        - mod_wsgi
        - httpd
    - name: Configure selinux
      action: seboolean persistent=yes name=httpd_can_network_connect state=true
      ignore_errors: True
    - name: Ensure apache is enabled
      action: service name=httpd state=started
    - name: Update apache configuration
      action: copy src=../config/synhak.org.conf dest=/etc/httpd/conf.d/synhak.org.conf
      notify:
        - reload apache
  handlers:
    - name: reload apache
      action: service name=httpd state=reloaded
- include: ../plays/mediawiki-update.yml
- include: ../plays/deploy-spiff.yml
- include: ../plays/configure-mailman.yml
- include: ../plays/update-phong.yml
